apiVersion: apps/v1
kind: Deployment
metadata:
  name: ce-deploy
  labels:
    tier: webserver
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-rolling
  labels:
    app: webserver
spec:
  replicas: 6
  selector:
    matchLabels:
      app: webserver
  strategy:
    type: RollingUpdate   
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: store-products:1.0
        name: calebespinoza
        ports:
        - containerPort: 80